{"trial_id": "0004", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.005, "conditions": [], "values": [0.005, 0.001, 0.0005, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "dropout", "default": 0.2, "conditions": [], "values": [0.2, 0.3, 0.4], "ordered": true}}, {"class_name": "Int", "config": {"name": "units_layer_1", "default": null, "conditions": [], "min_value": 64, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_2", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_3", "default": null, "conditions": [], "min_value": 16, "max_value": 64, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_4", "default": null, "conditions": [], "min_value": 8, "max_value": 32, "step": 8, "sampling": "linear"}}], "values": {"learning_rate": 0.0001, "activation": "relu", "dropout": 0.2, "units_layer_1": 64, "units_layer_2": 32, "units_layer_3": 32, "units_layer_4": 16, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 3, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 76, in on_epoch_end\n    self._save_model()\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/keras_tuner/src/engine/tuner_utils.py\", line 86, in _save_model\n    self.model.save_weights(write_filepath)\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/h5py/_hl/files.py\", line 564, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jules/.pyenv/versions/3.12.11/lib/python3.12/site-packages/h5py/_hl/files.py\", line 244, in make_fid\n    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"h5py/_objects.pyx\", line 56, in h5py._objects.with_phil.wrapper\n  File \"h5py/_objects.pyx\", line 57, in h5py._objects.with_phil.wrapper\n  File \"h5py/h5f.pyx\", line 122, in h5py.h5f.create\nFileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = 'mlp_analysis_results_20250826_231428/snn_ids_hyperband/trial_0004/checkpoint.weights.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)\n"}